### PR TITLE
[JENKINS-44054] Add plugin description to POM

### PR DESCRIPTION
**Pull request by varyvol**
[JENKINS-44054](https://issues.jenkins-ci.org/browse/JENKINS-44054)

@reviewbybees @gboissinot @marshall777

### CODE REVIEW

**Comment by varyvol** [comment]
@reviewbybees done.

**Comment by varyvol** [comment]
@gboissinot @marshall777 did you have the opportunity to review this?

**Comment by marshall777** [comment]
Seems Goodwin to me.
Sorry for the delay.

**Comment by varyvol** [comment]
@marshall777 no worries at all, much appreciated. Thanks!

**Pull request merged**
