### PR TITLE
Revert "[FIXED JENKINS-9104] Veto killing mspdbsrv.exe"

### PR DESCRIPTION
**Pull request by gboissinot**
Reverts jenkinsci/msbuild-plugin#19

### CODE REVIEW

**Comment by daniel-beck** [comment]
@gboissinot Any particular reason for the revert?

CC @DanielWeber

**Comment by DanielWeber** [comment]
@gboissinot was something wrong with my commit?

**Comment by gboissinot** [comment]
No problem, Pull request merged.

**Comment by DanielWeber** [comment]
@gboissinot But you just merged this PR, which reverts mine (PR 19), and then created a new release of the msbuild plugin (without my change).

If there is a problem with my PR 19, please let me know so that I can fix it.

**Comment by gboissinot** [comment]
@DanielWeber Sorry for this wrong manipulation. Please make a new pull request.

**Comment by estyrke** [comment]
I made a try at reviving @DanielWeber 's code. Let me know if I'm out of line here, but I thought I'd spare you others the work.

**Comment by DanielWeber** [comment]
@estyrke Not out of line, thanks :)

**Pull request merged**
